### ISSUE TITLE
请问后续会适配消费记录这个页面吗

### ISSUE THREAD

**Issue by hug1013** [marioplus/steam-price-converter#1]
https://store.steampowered.com/account/history/ 请问后续会适配这个页面吗

**Comment by marioplus** [comment]
已经适配：https://github.com/marioplus/steam-price-converter/releases/tag/v1.0.8

**Comment by marioplus** [comment]
![image](https://user-images.githubusercontent.com/26264731/194691801-ac809526-c945-4404-8167-9b770826b428.png)
