### ISSUE TITLE
[BUG]南非区游戏价格超过R1000价格转换失败

### ISSUE THREAD

**Issue by Gensokyo1995** [marioplus/steam-price-converter#10]
**bug 描述**
南非区游戏价格超过R1000会价格转换失败

**预期**
可以转换南非区R1000以上的价格

**截图**
![image](https://github.com/marioplus/steam-price-converter/assets/43993884/089bb4a4-d7b3-43b2-a0ab-909250d35c37)
控制台提示
![image](https://github.com/marioplus/steam-price-converter/assets/43993884/4253455b-9e88-400c-acb7-8af19261dd45)
console.error(e);
console.error("\u8F6C\u6362\u5931\u8D25\u8BF7\u5C06\u4E0B\u5217\u5185\u5BB9\u53CD\u9988\u7ED9\u5F00\u53D1\u8005\uFF0C\u53F3\u952E > \u590D\u5236(copy) > \u590D\u5236\u5143\u7D20(copy element)");
console.error("\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193\u2193");
console.error(element);
console.error("\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191\u2191");

**Comment by marioplus** [comment]
我没有南非的梯子，无法测试，麻烦按照我下面说的测试下。
按照下图的方式打开脚本编辑界面
![image](https://github.com/marioplus/steam-price-converter/assets/26264731/286f2749-d69e-44cc-9cff-016f56e708be)
在 1692 行添加 `\s`
![image](https://github.com/marioplus/steam-price-converter/assets/26264731/4e0f7327-f638-40e6-9979-f45542025807)
然后按下快捷键 <kbd>ctrl</kbd> + <kbd>s</kbd>
![image](https://github.com/marioplus/steam-price-converter/assets/26264731/673d2486-132c-464d-8cf5-727085cd3e56)
然后返回商店界面查看是否修复。

**Comment by Gensokyo1995** [comment]
十分感谢，按截图操作后可以了，但是不知道截图中的\s前面是否有空格，我测试了下没有空格的话还是不行，加上空格就好了
1692行
`    const matches = content.match(new RegExp("(?<=^\\D*)\\d+[\\d,. \s]*?(?=\\D*$)")); `
![image](https://github.com/marioplus/steam-price-converter/assets/43993884/71137b90-f285-4094-ab0b-7d36defcdead)

**Comment by marioplus** [comment]
修复自 [v2.1.1](https://github.com/marioplus/steam-price-converter/releases/tag/v2.1.1)
