### ISSUE TITLE
[BUG]网页端使用正常，steam++版本没有效果

### ISSUE THREAD

**Issue by EndlessSky512** [marioplus/steam-price-converter#12]
**bug 描述**
网页端使用正常，steam++版本没有效果

**如何重现**
重现该问题的步骤:
1. 进入 'steam++'，载入插件 ‘steam-price-converter.user.steam++.js’
2. 进入 'steam客户端'
3. 插件无效

**预期**
在steam客户端正常运行

**截图**
网页端：
![image](https://github.com/marioplus/steam-price-converter/assets/56494908/3b108c05-6dad-45c6-b302-3bee09d8056d)
客户端：
![image](https://github.com/marioplus/steam-price-converter/assets/56494908/0e6059be-1b0a-4549-83dd-a44e5a3fa3c0)
![image](https://github.com/marioplus/steam-price-converter/assets/56494908/2e61ca1f-8673-4017-b7dc-061a8b2afd6b)
steam++的划词翻译和史低查询插件运行正常：
![image](https://github.com/marioplus/steam-price-converter/assets/56494908/cfc42199-1de8-47cc-8994-8039354f3843)

**猜测**
未知

**环境（请填写以下信息）:**
 - OS: Windows 11 家庭中文版 22H2
 - Steam 8.33.9.23
 - Steam++ 2.8.6

**附加信息**
问题原因未知，烦请告知如何查看steam客户端内浏览器输出的log信息，应该会有帮助

**Comment by marioplus** [comment]
steam++自己的原因导致不兼容，不再兼容。
