### ISSUE TITLE
[BUG]脚本失效

### ISSUE THREAD

**Issue by Gensokyo1995** [marioplus/steam-price-converter#13]
**bug 描述**
在steam页面脚本失效，价格没有进行转换

**如何重现**
重现该问题的步骤:
进入steam页面，脚本没有生效

**预期**
价格可以进行转换

**截图**
控制台报错
![image](https://github.com/marioplus/steam-price-converter/assets/43993884/44c32ca8-2267-4d71-9be7-ba3cd6df8049)
![image](https://github.com/marioplus/steam-price-converter/assets/43993884/cedd71c7-d7cb-4c4f-b8ea-2f926774e44d)

**附加信息**
大概2.10下午就这样了，过年还麻烦大佬了，希望有空的时候看看，脚本挺好用的，突然看不到转换后的价格有点不习惯了

**Comment by marioplus** [comment]
v2.3.3 已修复

**Comment by Gensokyo1995** [comment]
> v2.3.3 已修复

感谢大佬，可以使用了
