### ISSUE TITLE
[BUG]商店显示价格不准确

### ISSUE THREAD

**Issue by Skaarf** [marioplus/steam-price-converter#14]
**描述**
账号在印尼区，账号余额显示正常，商店页面显示价格会自动*%，即游戏实际价格为26.1，商店页面显示价格为0.26。
使用非印尼账号在购物车切换印尼区后测试问题依旧复现。
![image](https://github.com/marioplus/steam-price-converter/assets/31014213/afbdbbd0-18a2-4d42-9403-ea3365b3d7ef)
![image](https://github.com/marioplus/steam-price-converter/assets/31014213/b4e13fb6-06d4-4340-bba3-17de2a427d84)

**猜测**
问题可能来源于商店显示印尼货币未精确到分，即.00。个人余额后面是精确到分的，所以显示正确。以下是账户交易记录截图，可以看到精确到分的余额转换都是正确的，未精确到分的转换都是不正确的。
![image](https://github.com/marioplus/steam-price-converter/assets/31014213/7bb8adbb-dc34-4fd7-b0e7-baa98b81a00f)

看了[之前的回复](https://github.com/marioplus/steam-price-converter/issues/10#issuecomment-1566109564)，发现1744行有个`price = price / 100`，尝试删除100后商店页面显示正常了，但是余额显示又不对了。

**Comment by marioplus** [comment]
[v2.3.5](https://github.com/marioplus/steam-price-converter/releases/tag/v2.3.5) 尝试修复了。你试试，我没有这个区域的账号，无法测试。

**Comment by Skaarf** [comment]
感谢大佬百忙之中抽空修复，目前显示已经正常了。
![image](https://github.com/marioplus/steam-price-converter/assets/31014213/ed4fa59f-48f9-4771-a5bb-aaa11e9ff768)
