### ISSUE TITLE
[BUG]2.3.6 通过商店页面获取区域代码失败

### ISSUE THREAD

**Issue by Gensokyo1995** [marioplus/steam-price-converter#15]
**bug 描述**
商店页面脚本失效，浏览器控制台提示通过商店页面获取区域代码失败
其他页面正常使用，只在商店页面失效

**如何重现**
重现该问题的步骤:
1. 打开任何游戏的商店页面，脚本无法转换价格
![image](https://github.com/marioplus/steam-price-converter/assets/43993884/25821021-b7ab-4dcc-9724-f08579539356)

**预期**
脚本正常使用

**截图**
![image](https://github.com/marioplus/steam-price-converter/assets/43993884/8d202f15-ce89-4cb0-99b5-50a4c5c27d73)

**环境（请填写以下信息）:**
 - Version  2.3.6

**附加信息**
2.3.5正常使用，更新后出错

**Comment by marioplus** [comment]
删除之后，重新安装试试

**Comment by marioplus** [comment]
未重现
![image](https://github.com/marioplus/steam-price-converter/assets/26264731/0c8a404c-cff0-4636-bf2f-a300f2e27222)

**Comment by Gensokyo1995** [comment]
呃，奇怪了，我用2.3.6这个页面都不行，重新安装也一样，降级到2.3.5是正常使用的

**Comment by marioplus** [comment]
![image](https://github.com/marioplus/steam-price-converter/assets/26264731/172f71db-6af4-4a84-8a21-bd663d6441e6)
按照此步骤删除脚本中的这行试试
![image](https://github.com/marioplus/steam-price-converter/assets/26264731/aded6a3d-23ee-4704-9be0-7dc242603354)

**Comment by Gensokyo1995** [comment]
> ![image](https://private-user-images.githubusercontent.com/26264731/307340852-172f71db-6af4-4a84-8a21-bd663d6441e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTY3NDIsIm5iZiI6MTcwODY5NjQ0MiwicGF0aCI6Ii8yNjI2NDczMS8zMDczNDA4NTItMTcyZjcxZGItNmFmNC00YTg0LThhMjEtYmQ2NjNkNjQ0MWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEzNTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZDQ0MGI4ODUyYzdmODI5OTZmNTZiMDIyYjNlNjU0N2FkM2M3ZWYzMTNlOTQzMTA0N2Q2MWYyMWEzNTMzOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Evv-OXoqd64qW6uI6sHULmT_TdGj3kyRaI7vqUcacNs) 按照此步骤删除脚本中的这行试试 ![image](https://private-user-images.githubusercontent.com/26264731/307340639-aded6a3d-23ee-4704-9be0-7dc242603354.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTY3NDIsIm5iZiI6MTcwODY5NjQ0MiwicGF0aCI6Ii8yNjI2NDczMS8zMDczNDA2MzktYWRlZDZhM2QtMjNlZS00NzA0LTliZTAtN2RjMjQyNjAzMzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEzNTQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhM2MzZGMxZjY5MmFhMGEzMGViZTk3YzQzMTZjZWIzNDQxYmExMGIwNTlhZGVlN2NlZTVkZjE1MmUyMWI1NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z8eL5qEsrbMrOn12AGrdCdB6xkfTOwn4ZUAXtMM6qkY)

删除后正常显示了

**Comment by marioplus** [comment]
v2.3.7已修复

**Comment by Gensokyo1995** [comment]
感谢，已经正常了
