### ISSUE TITLE
[BUG]斯里兰卡是南亚区用的是USD结算，麻烦作者能改下货币吗

### ISSUE THREAD

**Issue by Gensokyo1995** [marioplus/steam-price-converter#16]
**bug 描述**
斯里兰卡是南亚区用的是USD结算，目前取的是LK货币汇率

**如何重现**
![image](https://github.com/marioplus/steam-price-converter/assets/43993884/8c62fa27-97cf-4e85-885c-167625cb1620)
![image](https://github.com/marioplus/steam-price-converter/assets/43993884/08a462d7-c443-431a-b51c-da953c493c06)

**预期**
修正货币结算汇率

**截图**
如果可以的话, 添加几张截图以帮助您更好的说明问题。

**猜测**
如果您关于该问题的怀疑方向，请在此处提供，以帮助我们更快的修复问题

**环境（请填写以下信息）:**
 - OS: [如: win]
 - Browser [如. chrome, safari]
 - Version [如. 100]

**附加信息**
在此处填写有关该问题的其他信息

**Comment by marioplus** [comment]
[v 2.4.1](https://github.com/marioplus/steam-price-converter/releases/tag/v2.4.1)已修复
