### ISSUE TITLE
[BUG] 俄区价格转换异常

### ISSUE THREAD

**Issue by kinoko117** [marioplus/steam-price-converter#17]
大佬，在某次更新后出现了俄区价格转换异常

1、商店页面
![image](https://github.com/user-attachments/assets/462018e8-0911-4d0b-9d3e-892e1b47a086)
![image](https://github.com/user-attachments/assets/e3c41884-460d-4375-9a60-c9ec45c64643)
![image](https://github.com/user-attachments/assets/c2de9aa0-66a0-4580-94b8-796efd65984b)
2、市场，有些正常有些不正常
  不正常：
![image](https://github.com/user-attachments/assets/893d8c97-0c06-4c7f-8e29-49ba13a2134e)
  正常：
![image](https://github.com/user-attachments/assets/86711b81-6d9b-4f00-b078-2d5d33e4f558)

**Comment by marioplus** [comment]
[v2.4.4](https://github.com/marioplus/steam-price-converter/releases/tag/v2.4.4) 已修复
