### ISSUE TITLE
[BUG]价格转换会无限循环加载

### ISSUE THREAD

**Issue by Gensokyo1995** [marioplus/steam-price-converter#19]
**bug 描述**
![image](https://github.com/user-attachments/assets/82959660-82e9-4317-85b2-d87e7ca4b19f)
![image](https://github.com/user-attachments/assets/644f36fb-cb8e-4617-b09c-9366c7fdaf85)
版本2.5.1，价格转换会无限循环加载，导致页面显示出现问题

**如何重现**
进入steam有价格显示的页面

**预期**
正常显示价格转换

**截图**
如果可以的话, 添加几张截图以帮助您更好的说明问题。

**猜测**
如果您关于该问题的怀疑方向，请在此处提供，以帮助我们更快的修复问题

**环境（请填写以下信息）:**
 - OS: window11 24H2
 - Browser edge Chrome QQ浏览器
 - Version 2.5.1

**附加信息**
在此处填写有关该问题的其他信息

**Comment by marioplus** [comment]
[v2.5.2](https://github.com/marioplus/steam-price-converter/releases/tag/v2.5.2)已修复

**Comment by Gensokyo1995** [comment]
感谢大大的快速修复
