### ISSUE TITLE
现在脚本有大概率和 Augmented Steam 插件的全球比价功能冲突。

### ISSUE THREAD

**Issue by breezywhizzy** [marioplus/steam-price-converter#2]
似乎是 Augmented Steam 插件更新到 2.4.0 才出现的问题，之前可以和谐共存，现在在开启价格转换脚本的情况下，Augmented Steam 的浮动全球比价功能会失效。

**Comment by marioplus** [comment]
![image](https://user-images.githubusercontent.com/26264731/208472342-9970fe83-81ee-45a8-a74c-b999fb0e44aa.png)
浮动全球比价功能，是指图上这个功能吗，如果是，在我这里变现良好。
![image](https://user-images.githubusercontent.com/26264731/208472635-d5f7044e-fbdd-4134-88fc-e94cae9b4d67.png)
Augmented Steam 版本也为 2.4.0

**Comment by marioplus** [comment]
有可能是因为 #5 ，更新下再试试

**Comment by Suntxx** [comment]
我也是这样，解决了吗
