### ISSUE TITLE
与Steam Inventory Helper扩展有冲突

### ISSUE THREAD

**Issue by Gensokyo1995** [marioplus/steam-price-converter#4]
脚本和扩展同时使用
![image](https://user-images.githubusercontent.com/43993884/208802710-5ca911aa-9f50-467a-b262-41d00cb2a83f.png)

只使用扩展
![image](https://user-images.githubusercontent.com/43993884/208802807-c0122f04-1466-45c3-8eee-4780f4b0515f.png)

扩展版本
![image](https://user-images.githubusercontent.com/43993884/208804696-77a56b18-2b6f-4da1-8f86-c4efd7480bc0.png)

**Comment by marioplus** [comment]
因本脚本和 steam inventory helper 会同时修改同一元素，想做兼容会影响没有安装此插件的人，故不做兼容，可以通过安装此[脚本](https://greasyfork.org/zh-CN/scripts/452652-steam%E4%BB%B7%E6%A0%BC%E8%BD%AC%E6%8D%A2-sih-%E9%80%82%E9%85%8D)临时解决。
