### ISSUE TITLE
[BUG] 使用这个插件换算 商店页面会有显示bug

### ISSUE THREAD

**Issue by hug1013** [marioplus/steam-price-converter#6]
使用这个插件换算 商店页面会有显示bug
这个问题已经很久导致我一直在使用另一个价格换算 没想到很久之后的今天 使用一下 bug依然在

<img width="535" alt="image" src="https://user-images.githubusercontent.com/86723248/210627835-9b8e70ca-4ab1-4f22-b9bd-e313e258191c.png">
<img width="535" alt="屏幕截图 2023-01-05 024527" src="https://user-images.githubusercontent.com/86723248/210627936-7232d492-a3c5-45cd-b72d-41bf561221d5.png">

**Comment by marioplus** [comment]
关闭其他插件，试试看。应该是和某个插件冲突。

**Comment by marioplus** [comment]
看起来有点像 #4

**Comment by marioplus** [comment]
缺少更多的反馈。先关闭
