### ISSUE TITLE
[BUG]今天脚本失效了，获取区域代码失败

### ISSUE THREAD

**Issue by Gensokyo1995** [marioplus/steam-price-converter#7]
**bug 描述**
![image](https://user-images.githubusercontent.com/43993884/229959333-b9032dfc-a37a-4441-9ab8-5e0f6df8ee23.png)

**如何重现**
重现该问题的步骤:
1. 进入 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 看见的异常行为

**预期**
对于改步骤您希望得到什么结果

**截图**
如果可以的话, 添加几张截图以帮助您更好的说明问题。

**猜测**
如果您关于该问题的怀疑方向，请在此处提供，以帮助我们更快的修复问题

**环境（请填写以下信息）:**
 - OS: [如: win]
 - Browser [如. chrome, safari]
 - Version [如. 100]

**附加信息**
在此处填写有关该问题的其他信息

**Comment by marioplus** [comment]
fixed in [v2.0.3](https://github.com/marioplus/steam-price-converter/releases/tag/v2.0.3)

**Comment by Gensokyo1995** [comment]
可以了，谢谢大佬
