### ISSUE TITLE
价格不准确

### ISSUE THREAD

**Issue by shuage121** [marioplus/steam-price-converter#8]
我发现获取的api的价格并不准确  获取的阿根廷区价格为：32.27290  实际上在百度查询到的价格为32.6797 我用国区的账号查看市场的订单发现非常接近于百度查询的结果

**Comment by marioplus** [comment]
调用的是免费的api，汇率不是实时更新的。如果你有更准确、实时性更高的api提供，可以适配，我个人认为这个误差在忍受范围内。
而且我本身也会在本地做一个小时的汇率缓存。不然每打开一个页面都要取请求汇率。网络不好的情况下体验不好。
