### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by luckywlb** [marioplus/steam-price-converter#9]
你好，steam价格转换器能封装一个可以自定义汇率的的组件吗？只需要美元转人民币就可以，谢谢

**Comment by luckywlb** [comment]
这种感觉更有应用场景

**Comment by marioplus** [comment]
可以说一下你的想法，自定义汇率我看不出有什么应用场景。你提到的美元转人名币，这本身就是一个确定的汇率了。如果自定义就不是美元转人名币了。

**Comment by marioplus** [comment]
[v2.1.0](https://github.com/marioplus/steam-price-converter/releases/tag/v2.1.0)已支持。
使用这个打开自定义汇率设置
```js
SpcManager.setUseCustomRate(true)
```
使用这个设置自定义的汇率
```js
SpcManager.setUseCustomRate(1)
```
